/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;

import java.util.Arrays;
import java.util.Random;

public class Library {
    public int[] roll(int n) {
        Random rand = new Random();
        int[] diceArray = new int[n];
        for (int i = 0; i <n; i++) {
            int diceRoll = rand.nextInt(6)+1;
            diceArray[i] = diceRoll;
        }
        return diceArray;
    }
    public boolean containsDuplicate(int[] array) {
        for (int i = 0; i < array.length; i++){
            for (int j = i+1; j < array.length; j++) {
                if (array[i] == (array[j])) {
                    return false;
                }
            }
        }
        return true;
    }

    public double average(int[] array) {
        double totalSum = 0;
        for (int i = 0; i < array.length; i++) {
            totalSum = totalSum + array[i];
        }
        double totalAverage = totalSum/array.length;
        return totalAverage;
    }

    public int[] arrayOfArrays(int[][] array) {
        double lowestAvg = 99999;
        int[] lowestArray = array[0];
        for (int i = 0; i < array.length; i++) {
            double totalSum = 0;
            for (int j = 0; j < array[i].length; j++) {
                totalSum = totalSum + array[i][j];
            }
            double totalAverage = totalSum/array[i].length;
            if (totalAverage < lowestAvg) {
                lowestAvg = totalAverage;
                lowestArray = array[i];
            }
        }
        return lowestArray;
    }
}
