/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class RestaurantTest {
    Restaurant McDonalds = new Restaurant("McDonalds", 0, 2);
    Restaurant BurgerKing = new Restaurant("BurgerKing", 0, 3);
    Review newReview = new Review("This place is great!", "Matt C.", 5, McDonalds);
    Review secondReview = new Review("Terrible", "John D.", 0, McDonalds);
    Review thirdReview = new Review("It was alright", "Barack O.", 3, McDonalds);
    Review fourthReview = new Review("Hur Dur", "Albert E.", 10, BurgerKing);

    @Test void constructorTest() {
        System.out.println(McDonalds.toString());
        System.out.println(BurgerKing.toString());
        System.out.println(newReview.toString());
    }

    @Test void addReviewTest() {
        McDonalds.addReview(newReview);
        McDonalds.addReview(secondReview);
        McDonalds.addReview(thirdReview);
        // test to add a review for a non-matching restaurant
        McDonalds.addReview(fourthReview);
        // prints McDonald's specific reviews
        System.out.println(McDonalds.reviews);

        //check to see if the rating was updated
        System.out.println(McDonalds.toString());
    }
}